name: Terraform Infrastructure Deployment

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Terraform on GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY1 }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Filesystem with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          ./trivy fs --exit-code 0 --no-progress .

      - name: Scan Docker Image with Trivy
        run: ./trivy image --exit-code 0 --no-progress myapp:latest

